### ISSUE TITLE
Slow down follow rate, manual entry or randomize timing?

### ISSUE THREAD

**Issue by laserjobs** [tlemens/twitter-mass-follow#1]
Got backed off after around 120 follows. Was able to follow manually after a few minutes but concerned that twitter is backing off due to too fast or exact timed follows. Previous to this I did about 500 unfollows without a hitch. Possibly be backed off due to actions? Anyways I was thinking that if there was a manual override for timing plus adding in some random milliseconds between follows would help alleviate the issue.

**Comment by tlemens** [comment]
Hi laserjobs,

thank you for opening the first issue.

Speed option is the top-prio feature for the next version. Coming this summer. ;)

**Comment by tlemens** [comment]
@laserjobs you can now set the follow/unfollow wait via settings. Cheers!
