### ISSUE TITLE
Avoiding Twitter Ban

### ISSUE THREAD

**Issue by medienoekonom** [tlemens/twitter-mass-follow#17]
Hi there, 

I would strongly suggest to build a randomizer around the follow event. anything between 500 - 1200ms. Twitter banned me within 5 Minutes when I tried to use it with 350ms. 

Cheers
Daniel

**Comment by tlemens** [comment]
Hi Daniel,

I don't think a randomizer would have saved you from banning. Instead you should stick with the default setting, or - if you get locked often - increase the wait, limit your follow sessions and take a longer break between the sessions.

Cheers
