### ISSUE TITLE
Add new followers to private list when following

### ISSUE THREAD

**Issue by kylemanna** [tlemens/twitter-mass-follow#18]
Hey,

Stumbled on your extension and think it works great!  Even better that it's open source.  Figured I'd share the only thing I think it's missing: the ability to add new followers to a private Twitter list to keep track of things.

Thoughts?

**Comment by tlemens** [comment]
Hi kylemanna,

thanks for the props! 

So people who follow you back will automatically be added to that private list?

**Comment by kylemanna** [comment]
Was thinking that the accounts that the extension mass follows will be added to the list so I can remember when and how I followed a certain account.  Perhaps under the follow settings there'd be an option to "Add to list ________ after following" and then the operation would be:
1. Follow person
2. Add person to list `x`
3. Wait for predefined follow timeout
4. Repeat.

**Comment by tlemens** [comment]
But what is the advantage of having this list? There is also a limit for users on a list. (5000)

**Comment by kylemanna** [comment]
The advantage is that it enable users to keep track of who was followed (also on what date) and potentially who followed back by reviewing the list.

The [Follwr extension](https://chrome.google.com/webstore/detail/followr/phbifpkhlenmpjndnmjppbdhcocdlalk?hl=en-US) has a client side log of it's actions. I find it handy.

Thanks for considering!

**Comment by benjaminspak** [comment]
@kylemanna I feel like you might be able to accomplish you would like with an IFTTT or Zapier recipe. I have used them for lists in the past and they worked like a charm.

**Comment by kylemanna** [comment]
Thanks for the update, I'll dig in.
