### ISSUE TITLE
Unfollow starting from the bottom

### ISSUE THREAD

**Issue by IvanRF** [tlemens/twitter-mass-follow#19]
I like the idea on issue #12 more, but another option is to start unfollowing from the bottom. That way, the oldest follow ups will be the first unfollows.

It could be an option on the settings. Then the extension scrolls all the way down and starts unfollowing in reverse order.

**Comment by tlemens** [comment]
Hi IvanRF,

i like the idea. It might take some time to get to the end though. :)

Do you have any thoughts on #12

**Comment by IvanRF** [comment]
Yes, you are right about that and sometimes the current auto scroll stops working. It happened with the Follow All option, I need to "help it" by scrolling manually in order to continue.

**Comment by tlemens** [comment]
Since #12 is now available I will close this issue.
