### ISSUE TITLE
Option: Skip profiles with no Bio

### ISSUE THREAD

**Issue by IvanRF** [tlemens/twitter-mass-follow#20]
Similar to other setting options, it would be useful to skip profiles with no `Bio` text.

Content example: `<p class="ProfileCard-bio u-dir" dir="ltr" data-aria-label-part=""></p>`

**Comment by benjaminspak** [comment]
I've been wanting this one as well :)

**Comment by tlemens** [comment]
This option is now available!

**Comment by benjaminspak** [comment]
You are slaying these features @tlemens !! <3
