### ISSUE TITLE
Users who block you

### ISSUE THREAD

**Issue by IvanRF** [tlemens/twitter-mass-follow#22]
I just saw this message while using the extension: `You have been blocked from following this account at the request of the user.`

Is there any way of knowing for which user that message was thrown?

**Comment by tlemens** [comment]
I am not sure... do you have the markup of the particular profile?

**Comment by IvanRF** [comment]
I don't know what you mean by markup. While the extension was following accounts, Twitter showed that message at the top of the page. However, I couldn't find any clue about which was the account who cause it.

**Comment by tlemens** [comment]
Ok... by markup I mean the HTML snippet of the particular profile... I will try to stop the extension next time I see the notification and check if the blocked-Status is visible

**Comment by IvanRF** [comment]
Today I saw this again and found the blocking user! 😈 
![2016-09-28_20-28-30](https://cloud.githubusercontent.com/assets/6751650/18936028/896ffb9c-85ba-11e6-8a05-eaadb520b87f.png)

The plugin shows "Successfully followed", but it was not 😄

**Comment by IvanRF** [comment]
When you implement #12, the timing event will help you here too since the button remained as "Follow" after the plugin tried to follow the blocking user.

**Comment by tlemens** [comment]
Ok ;) So now we know there is no Icon or text saying "The User Blocks you". As you suggested we have to use The timer to check The follow success.

**Comment by tlemens** [comment]
You now get a warn log 'Follow was rejected by Twitter' on the profile... this indicates that the user blocked you

**Comment by IvanRF** [comment]
👍 thanks!
