### ISSUE TITLE
Performance: Hide images

### ISSUE THREAD

**Issue by IvanRF** [tlemens/twitter-mass-follow#23]
When you handle too many profiles while scrolling, the performance can be improved if you hide the profile images.
For example, with this CSS the network download and the CPU processing is much less:
`
.ProfileCard-bg { background-image: none !important; }
`

This could be added as an option, or by default when someone clicks on Follow All or Unfollow All.

**Comment by benjaminspak** [comment]
That's a great idea!

**Comment by Overtorment** [comment]
Great idea, just tested it. Also, hiding avatars works

```
var style=document.createElement('style');
style.type='text/css';
var css = '.ProfileCard-avatarImage { display: none; } .ProfileCard-bg { display: none; }' ;
if(style.styleSheet){
    style.styleSheet.cssText= css;
}else{
    style.appendChild(document.createTextNode(css));
}
document.getElementsByTagName('head')[0].appendChild(style);
```

**Comment by tlemens** [comment]
Version 13 includes a setting "Hide profile avatar and background images while (un)following"
