### ISSUE TITLE
Starting position ???

### ISSUE THREAD

**Issue by vic2pal** [tlemens/twitter-mass-follow#25]
Hello..
Thanx alot for your "mass great" tool
but I've one important suggestion that will make the tool more and more effective..
(Starting position)
Yeah.. imagine that I opend one account's followers page .. and I want to follow 100 from there
but I don't want to follow the first 100

there must be a mechanism to do so.. either by adding an option to start following/unfollowing from the screen position and down (or up) , or by adding an option to skip first ( NUMBER )

I think that will make your tool a supreme one 😚😚
all the love dude ♥

**Comment by tlemens** [comment]
Hi vic2pal, thank you for the props. ;)

What is the starting position useful for? Why would you like to skip the first 100?

**Comment by vic2pal** [comment]
You're welcome Telmens :)

I'm using your beautiful tool to follow one's followers, and I think that his follower might like my account as they like his cuz both of us has the same interests..
Now, I follow the first 1000 and after one or two days around 150-200 of them follow me back..
Then I used your tool again to unfollow those who didn't follow me back (in order to keep a balance between my followings and followers"
After that I wanna come back again and skip the first 1000 and start to follow the next 1000..... and so on

I'm facing the problem that I mention above :)

Note that I have a third suggestion to do so..
not to start from screen position nor to skip a specific number of accounts..
It's (start from bottom) option, so I could scroll down to round 2000 account, then start from bottom and follow 1000.. by that I'll skip the first 1000

Thanks again dude 😍😍

**Comment by tlemens** [comment]
You can use the setting "Skip already once followed profiles" for your use case.  The extension will skip all profiles you have followed before and autoscrolls down for you. If the autoscrolling does not work, please refresh the page. Hope this helps.

**Comment by vic2pal** [comment]
I tried it now. it worked and skipped just a few profiles.. Then I scrolled down manually and it stopped skipping
does my manual scrolling has any relation??

**Comment by tlemens** [comment]
The scrolling does not affect the "skip followed" option... if it does not scroll down automatically, please refresh the Page before using the buttons

**Comment by vic2pal** [comment]
The problem is not with scrolling.. scrolling works well
The problem is that the tool skipped only a few profiles around 20
and complete to follow people that I follow before and then unfollowed them

**Comment by tlemens** [comment]
Are you sure you followed them before? It should actually skip all profiles you have ever followed before. Also if you remove the Extension the Data is lost.

**Comment by vic2pal** [comment]
Yes I'm sure that I've followed them before..
But I'm not sure if I followed them by this extension or with another "simple one" before
Maybe your extension skip the profiles that only followed by it ???

it's the only explanation for what happened

**Comment by tlemens** [comment]
Yes only those profiles followed with this extension can be stored and used later... you should only use this extension ;)

**Comment by vic2pal** [comment]
very nice.. you are awesome man..
I'm officially using it now and it's really Perfect
I wonder how can I thank you 😊

**Comment by tlemens** [comment]
I am glad you like it... feedback and suggestions are always welcome
