### ISSUE TITLE
Stack trace, line 246 of twitter_mass_follow.js

### ISSUE THREAD

**Issue by QwertyZW** [tlemens/twitter-mass-follow#27]
Great extensions btw.

Ran into a situation where this.currentProfile of line 246 of https://github.com/tlemens/twitter-mass-follow/blob/master/src/javascripts/twitter_mass_follow.js is undefined. 

Not exactly sure what the branch there is supposed to be doing but I think it's supposed to scroll down the page when there aren't any more profiles in the current DOM. Correct?

**Comment by tlemens** [comment]
You are right: Focus the current last profile to load more profiles... it should never be undefined... are you able to reproduce this error?

**Comment by QwertyZW** [comment]
I haven't tried but I believe you should able to recreate it by minimizing your window's height and then going onto a page of followers (such that the prompt shows) 

If not it might have been something else, it happened when I visited some random username's followers list while my devtools might have been open and docked to the bottom. Really I can't recall how I ran into the error, I will try recreating it over the weekend if I get time.

**Comment by tlemens** [comment]
Since the "scroll to bottom" no longer depends on focusing the last profile, this issue should be resolved.
