### ISSUE TITLE
Add people to list/on follow

### ISSUE THREAD

**Issue by QwertyZW** [tlemens/twitter-mass-follow#29]
In twitter you can create private and public lists.

I extended this package to add people to lists on follow. The problem was twitter kept locking the account out due to automated behavior 

I did it by automating the required clicks to add a username to the list, with timeouts between the clicks as needed.

I can look into sharing the code if you'd like to take a look at it.

**Comment by tlemens** [comment]
While developing you can uncomment the clickBtn in profile.js. So it won't actually follow, but act like.

Unfortunately you can only add up to 5000 members to a list.
