### ISSUE TITLE
"unfollowed profiles will be skipped" per account

### ISSUE THREAD

**Issue by Roayati** [tlemens/twitter-mass-follow#3]
Hi Is "unfollowed profiles will be skipped" featured store globally for all accounts used in same browser or it's based on account, and Is there any way to know skipped profiles ?

**Comment by tlemens** [comment]
Hi Roayati,

it is per-account, so you can use the extension with different accounts on the same computer.

When a profile gets skipped, there is a log message "already unfollowed once" on the profile.
