### ISSUE TITLE
Minimum days to unfollow has stopped working recently

### ISSUE THREAD

**Issue by ghost** [tlemens/twitter-mass-follow#32]
I've been using this tool for about a month now and lately, I see that the minimum days to unfollow has been bugging. It skips ten or so users then, then unfollows the rest. I don't know if this is a twitter change or a bug. I believe this may be an issue with the cache.

**Comment by tlemens** [comment]
Still not working?

Did you use the extension to follow? You also need to use the same computer for following and unfollowing . Also once you remove the extension, the data is lost.

It is working for me.

**Comment by ghost** [comment]
So I used this extension for about two months and everything worked fine. Then, all of a sudden, it stopped taking into consideration the number of days followed when I was unfollowing people. 

I then removed the extension and added it again. As you have mentioned, the data was lost, but after a couple of days, the extension worked fine and took in to consideration the number of days followed whilst unfollowing.

With that said, I strongly believe that the cache was full. Anyway to fix that other than removing and adding the extension?

**Comment by tlemens** [comment]
The data is stored in the chrome local storage, which is unlimited.

**Comment by tlemens** [comment]
I will close this issue since it is working again. Please ping me back if the problem pops up again.
