### ISSUE TITLE
Autoscroll stopped working

### ISSUE THREAD

**Issue by tlemens** [tlemens/twitter-mass-follow#35]
> I love this extension but its stopped working for me. This used to work but now follows like 12 accounts then says ' no more profiles found' when there are loads of accounts to follow? Please can you help.

> 
> I have  Mass Follow for Twitter Chrome extension installed. When I click on "follow all" or "unfollow all" button on my Twitter, the extension only unfollows the first page. 
> It doesn't automatically load the next page as it always used to in the past, in order to continue unfollowing all my non followers. 
> This makes me have to manually scroll down so that the extension can follow or unfollow.
> I think there is an error. This has never happened until today.
> Please help?

**Comment by broerse** [comment]
Autoscroll stopped working for me too a few days ago.

**Comment by tlemens** [comment]
Please update the extension... this should now work again

**Comment by broerse** [comment]
Confirming it works again. Thanks!
