### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by koravadi** [tlemens/twitter-mass-follow#42]
This is a very good extension. Here are couple of ideas, if we can add that will be great. I downloaded thd code and try to build as per the instructions not able build the code throwing errors.
1. Skip the profile that has followers less than some number
2.Only consider profile that is country specific.

Pls share steps to setup build env, so that i can make change and test the code.

**Comment by tlemens** [comment]
The steps are in the README. You have to use the gulp tool to build/develop.

Please also give your issue a meaningful name and focus on one topic. "New feature" is too broad.
