### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Zack673** [tlemens/twitter-mass-follow#43]
extension.js:
import TwitterMassFollow from 'twitter_mass_follow.js'

Uncaught SyntaxError: Unexpected identifier

Fresh source code, loaded into Chrome as Extension, above error is showing up for line 1 in extension.js and no "Follow all" or Mass Follow Menu is coming up.

Main Issue: Compiled SRC Code "Loaded Unpacked" shows no Mass Follow Menu when on Following/Followers Page, whats wrong here?

**Comment by tlemens** [comment]
First you have to build the extension. Please read the README with the instructions.
