### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Axisar** [tlemens/twitter-mass-follow#46]
Hi.
can you make random time interval between follow/unfollow actions in user set range?
i.e. instead of permanent pause (example: 1000ms) add ability to set range example:1000-5000ms

**Comment by tlemens** [comment]
The new extension for the new Twitter provides those: https://chrome.google.com/webstore/detail/mass-follow-for-new-twitt/fppndcbifafladddggjjhoopbkakjdlc
