### ISSUE TITLE
New twitter interface

### ISSUE THREAD

**Issue by ucelme** [tlemens/twitter-mass-follow#48]
Please, adopt your plugin under new twitter interface. It works much more faster and more convenient than old. Your plugin don't work with new interface.

**Comment by tlemens** [comment]
How can I access/use the new Twitter interface?

**Comment by ucelme** [comment]
I see on https://twitter.com/ "Try new Twitter" and then it switch to new interface.

**Comment by tlemens** [comment]
I don't see it ... may be they are doing some tests with the new design and just a few accounts are able to test it

**Comment by itsmutai** [comment]
Tlemens the issue is now twitterwide. Everyone has the new interface i believe including you...Can you kindly help those who are attached to this extension....PLEASE

**Comment by itsmutai** [comment]
Tlemens the issue is now twitterwide. Everyone has the new interface i believe including you...Can you kindly help those who are attached to this extension....PLEASE

**Comment by itsmutai** [comment]
Tlemens the issue is now twitterwide. Everyone has the new interface i believe including you...Can you kindly help those who are attached to this extension....PLEASE

**Comment by tlemens** [comment]
Working on it...

**Comment by itsmutai** [comment]
Anything coming soon?

**Comment by tlemens** [comment]
Good news: https://chrome.google.com/webstore/detail/mass-follow-for-new-twitt/fppndcbifafladddggjjhoopbkakjdlc
