### ISSUE TITLE
Plugin doesn't appear to be working 

### ISSUE THREAD

**Issue by benjaminspak** [tlemens/twitter-mass-follow#49]
The interface no longer appears on the followers and following pages in Chromium
Version 71.0.3578.98 (Official Build) snap (64-bit). Was working two days ago.

**Comment by johnnyz** [comment]
Just updated and still not working. Is there any word on an update? I appreciate the hard work @tlemens!

**Comment by tlemens** [comment]
Hi @benjaminspak ... still not working? If you are using the new Twitter Interface you will need to use the following extension: https://chrome.google.com/webstore/detail/mass-follow-for-new-twitt/fppndcbifafladddggjjhoopbkakjdlc
