### ISSUE TITLE
 account restricted

### ISSUE THREAD

**Issue by soulpull** [tlemens/twitter-mass-follow#51]
account restricted with this plugin,maybe twitter change its rules or maybe this plugin have no random time setting,so it needs to update with this plugin

**Comment by tlemens** [comment]
I just released the new extension for the new Twitter interface:
https://chrome.google.com/webstore/detail/mass-follow-for-new-twitt/fppndcbifafladddggjjhoopbkakjdlc

With the new extension you can set Ranges (Min - Max) for following and unfollowing intervals. Hope this helps.
