### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by fiazfqk** [tlemens/twitter-mass-follow#52]
I am using window 10 with chrome Version 75.0.3770.90 (Official Build) (64-bit)
no follow or unfollow manu appear anymore

**Comment by tlemens** [comment]
Hi @fiazhnd
if you are using the new Twitter interface you need to use the following extension: https://chrome.google.com/webstore/detail/mass-follow-for-new-twitt/fppndcbifafladddggjjhoopbkakjdlc
