### ISSUE TITLE
Avoid following profiles with no description and no picture

### ISSUE THREAD

**Issue by jfsmig** [tlemens/twitter-mass-follow#6]
Great tool!

Though I would like to focus on active profiles, and my personal-subjective-arbitrary heuristic tell me to avoid profiles with no description at all, and those with no picture.

**Comment by tlemens** [comment]
Hi jfsmig,

thank you for the feedback and the suggestions. I will add an option to skip profiles with no image. Not sure about the "no-description"-option yet.

**Comment by tlemens** [comment]
@jfsmig version 2.0 is out with "Profile image required" option. Please check it out and provide feedback.

**Comment by jfsmig** [comment]
Thanks! It works great :)
