### ISSUE TITLE
Is there anyway to export the list of already followed?

### ISSUE THREAD

**Issue by laserjobs** [tlemens/twitter-mass-follow#7]
Just wondering if there is a way to export the list of people already followed. It looks like the data is stored in local storage but I can't seem to find a way to export the data. I did try the extension Storage Area Explorer but I can't seem to find a page to extract the data from. Thanks for any help.

**Comment by tlemens** [comment]
You have to fetch the data and provide a Download: http://stackoverflow.com/questions/23160600/chrome-extension-local-storage-how-to-export

Hope this helps
